# -*- coding: utf-8 -*-
"""Problem-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlW-BQGBo2q3feICYKB7ce1XGdE-8d-b
"""

def factorial(n):
  if n==1:
    return 1
  else:
    return n*factorial(n-1)
if __name__ == '__main__':
  n=int(input())
  result=factorial(n)
  print(result)