# -*- coding: utf-8 -*-
"""Problem-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_TYmtuSVYRvKcl-eXRSfwAuvx6pENvm
"""

def fibonacci(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fibonacci(n-1)+fibonacci(n-2)
if __name__ == '__main__':
  n=int(input())
  result=[]
  for i in range(n):
    result.append(fibonacci(i))
  print(result)