# -*- coding: utf-8 -*-
"""Problem-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wSxwAb6Q7aKpD74VT0KibTJRPZI2R-s_
"""

def isPalindrome(string):
  string=string.casefold()
  if str(string) == str(string)[::-1]:
    if len(string)%2==0:
      print("Even Palindrome")
    else:
      print("Odd Palindrome")
  else:
    print("Not a Palindrome")

if __name__ == '__main__':
  string=str(input())
  isPalindrome(string)